apiVersion: apps/v1
kind: Deployment
metadata:
  name: profileapi
  labels:
    app: azure-user-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      service: profileapi
  template:
    metadata:
      labels:
        app: azure-user-profile
        service: profileapi
    spec:
      containers:
        - name: profileapi
          image: abastiuchenkoazcontainerregistry.azurecr.io/profileapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: profileapi
  labels:
    app: azure-user-profile
    service: profileapi
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: profileapi