# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  profileapi:
    image: profileapi
    build:
      context: ProfileAPI/.
      dockerfile: Dockerfile
    ports:
      - 8001:443
      - 8000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS="https://+;http://+"
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ProfileAPI.pfx 
    volumes:
      - $HOME/.aspnet/https:/https/:ro
      - $HOME/.vsdbg:/remote_debugger:rw
    restart: always
