# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  profileapi:
    ports:
      - 5263:5263
      - 7263:7263
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7263;http://+:5263
      - ASPNETCORE_HTTPS_PORT=7263
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ProfileAPI.pfx
    volumes:
      - ~/.aspnet/https:/https/:ro
      - ~/.microsoft/usersecrets/dfc8ff81-bfcb-4463-addf-038e4d3039b0:/home/appuser/.microsoft/usersecrets/dfc8ff81-bfcb-4463-addf-038e4d3039b0